- name: "Create victoriametrics service file"
  ansible.builtin.template:
    src: "victoriametrics.service.j2"
    dest: "/etc/systemd/system/victoriametrics.service"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: "Restart VictoriaMetrics"

- name: "Create victoriametrics configuration file"
  ansible.builtin.template:
    src: "promscrape.yml.j2"
    dest: "{{ victoriametrics_single_config_dir }}/promscrape.yml"
    mode: "0644"
    owner: "{{ victoriametrics_single_system_user }}"
    group: "{{ victoriametrics_single_system_group }}"
  notify: "Restart VictoriaMetrics"
