- name: "Add victoriametrics group"
  ansible.builtin.group:
    name: "{{ victoriametrics_single_system_group }}"
    state: "present"

- name: "Add victoriametrics as system user"
  ansible.builtin.user:
    name: "{{ victoriametrics_single_system_user }}"
    group: "{{ victoriametrics_single_system_group }}"
    shell: "/bin/false"
    system: true
    create_home: false
    state: "present"

- name: "Create victoriametrics data and configuration directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ victoriametrics_single_system_user }}"
    group: "{{ victoriametrics_single_system_group }}"
    mode: "0755"
  loop:
    - "{{ victoriametrics_single_data_dir }}"
    - "{{ victoriametrics_single_config_dir }}"
  loop_control:
    label: "{{ item }}"

- name: "Download victoriametrics binary to tmp folder"
  ansible.builtin.get_url:
    url: "{{ victoriametrics_single_download_url }}"
    dest: "/tmp/victoria-metrics.tar.gz"
    mode: "0644"

- name: "Extract victoriametrics binary to /tmp"
  ansible.builtin.unarchive:
    src: "/tmp/victoria-metrics.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: "Move victoriametrics binary to {{ _victoriametrics_binary_install_dir }}"
  ansible.builtin.copy:
    src: "/tmp/victoria-metrics-prod"
    dest: "{{ _victoriametrics_binary_install_dir }}/victoria-metrics-prod"
    mode: "0755"
    remote_src: true

- name: "Cleanup victoriametrics binary in /tmp"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/tmp/victoria-metrics-prod"
    - "/tmp/victoria-metrics.tar.gz"
  loop_control:
    label: "{{ item }}"
