---
# tasks file for victoriametrics_single
- name: "Check if victoriametrics binary is already installed"
  ansible.builtin.stat:
    path: "{{ _victoriametrics_binary_install_dir }}/victoria-metrics-prod"
  register: victoriametrics_binary_installed

- name: "Get installed version of victoriametrics"
  ansible.builtin.shell: "{{ _victoriametrics_binary_install_dir }}/victoria-metrics-prod -version | cut -d '-' -f 6"
  register: victoriametrics_installed_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  when: victoriametrics_binary_installed.stat.exists

- name: "Include install tasks"
  ansible.builtin.include_tasks: "install.yml"
  when: (not victoriametrics_binary_installed.stat.exists) or
        (victoriametrics_installed_version.stdout != victoriametrics_single_version) or
        (victoriametrics_single_force_install)

- name: "Include config tasks"
  ansible.builtin.include_tasks: "config.yml"

- name: "Ensure victoriametrics service is started and enabled"
  ansible.builtin.service:
    name: "victoriametrics"
    state: "started"
    enabled: true
