---
# handlers file for victoriametrics_single

- name: "Restart VictoriaMetrics"
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: "victoriametrics"
    state: "restarted"
