---
driver:
  name: docker
dependency:
  name: galaxy
  options:
    ignore-errors: true
platforms:
  - name: molecule-systemd-ubuntu-22.04
    image: msterhuj/molecule-systemd-ubuntu-22.04:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
